name: Build releases

on:
  push:
    tags:
    - "v*"

jobs:
  Build:
    name: Build all releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.14.7"
      - name: Build for Linux (amd64)
        env:
          GOOS=linux
          GOARCH=amd64
        run: go build -o ./nordsyd-linux-amd64 main.go

      - name: Build for Linux (386)
        env:
          GOOS=linux
          GOARCH=386
        run: go build -o ./nordsyd-linux-386 main.go

      - name: Build for macOS (amd64)
        env:
          GOOS=darwin
          GOARCH=amd64
        run: go build -o ./nordsyd-darwin-amd64 main.go

      - name: Build for macOS (386)
        env:
          GOOS=darwin
          GOARCH=386
        run: go build -o ./nordsyd-darwin-386 main.go

      - name: Build for Windows (amd64)
        env:
          GOOS=windows
          GOARCH=amd64
        run: go build -o ./nordsyd-windows-amd64.exe main.go

      - name: Build for Windows (386)
        env:
          GOOS=windows
          GOARCH=386
        run: go build -o ./nordsyd-windows-386.exe main.go

      - name: Build for Windows (arm)
        env:
          GOOS=windows
          GOARCH=arm
        run: go build -o ./nordsyd-windows-arm.exe main.go

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          prelease: true
          files: |
            nordsyd-linux-amd64
            nordsyd-linux-386
            nordsyd-darwin-amd64
            nordsyd-darwin-386
            nordsyd-windows-amd64.exe
            nordsyd-windows-386.exe
            nordsyd-windows-arm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}